# Generated by Django 5.0 on 2024-07-13 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission'),
        ('form_layouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_regular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('reaming', models.FloatField()),
                ('date', models.DateField()),
                ('items', models.JSONField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.cafe')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_layouts.regular_customer')),
            ],
        ),
    ]
