# Generated by Django 5.0 on 2024-07-23 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission'),
        ('form_layouts', '0003_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('sendDate', models.DateField()),
                ('sendTime', models.TimeField()),
                ('receiveTime', models.TimeField(blank=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.cafe')),
            ],
        ),
    ]
