# Generated by Django 5.0 on 2024-07-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission'),
        ('form_layouts', '0005_alter_kot_receivetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kot_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.cafe')),
            ],
        ),
    ]
