# Generated by Django 5.0 on 2024-08-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_layouts', '0008_kot_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='kot',
            name='table',
            field=models.CharField(default='Table', max_length=50),
        ),
    ]
