# Generated by Django 5.0 on 2024-09-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_layouts', '0009_kot_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='kot',
            name='print',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
