# Use an official Nginx image
FROM nginx:latest

# Copy custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static files from the correct directory
COPY staticfiles /usr/share/nginx/html/static
