# Generated by Django 5.0 on 2024-07-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission'),
        ('forms', '0004_order_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.cafe'),
        ),
    ]
