# Generated by Django 5.0 on 2024-07-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission'),
        ('forms', '0005_order_list_cafe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.cafe')),
            ],
        ),
    ]
