# Generated by Django 5.0 on 2024-07-09 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission'),
        ('forms', '0006_number_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tax', models.FloatField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.cafe')),
            ],
        ),
    ]
