# Generated by Django 5.0 on 2024-07-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='pieces_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
