# Generated by Django 5.0 on 2024-07-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_menu_date_menu_discount_menu_pieces_qty_menu_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='total_pieces',
            field=models.IntegerField(default=1),
        ),
    ]
