# Generated by Django 5.0 on 2024-07-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_menu_total_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default='Beverages', max_length=100),
        ),
    ]
