# Generated by Django 5.0 on 2024-07-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
