# Generated by Django 5.0 on 2024-07-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_order_list_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='unpaid',
            field=models.BooleanField(default=False),
        ),
    ]
